# -*- coding: utf-8 -*-
"""pose_estimation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0-FYxQEpHwJa6bBkkkxUWOSInZjziKn
"""

import cv2
import numpy as np
import os

def load_pose_model():
    proto_file = "./openpose/models/pose/coco/pose_deploy_linevec.prototxt"
    weights_file = "./openpose/models/pose/coco/pose_iter_440000.caffemodel"

    if not os.path.exists(proto_file) or not os.path.exists(weights_file):
        raise FileNotFoundError("OpenPose COCO model files not found. Please check paths!")

    net = cv2.dnn.readNetFromCaffe(proto_file, weights_file)
    return net

def extract_keypoints(image, pose_model, threshold=0.1):
    in_width = 368
    in_height = 368

    frame_height, frame_width = image.shape[:2]
    inp_blob = cv2.dnn.blobFromImage(image, 1.0/255, (in_width, in_height),
                                     (0,0,0), swapRB=False, crop=False)
    pose_model.setInput(inp_blob)
    output = pose_model.forward()

    points = []
    n_points = 18  # COCO model

    for i in range(n_points):
        prob_map = output[0, i, :, :]
        _, prob, _, point = cv2.minMaxLoc(prob_map)

        x = (frame_width * point[0]) / output.shape[3]
        y = (frame_height * point[1]) / output.shape[2]

        if prob > threshold:
            points.append((x / frame_width, y / frame_height))  # normalized points
        else:
            points.append((0, 0))  # if not detected, fallback to (0,0)

    return points

# import torch
# import numpy as np

# def load_pose_model():
#     # Load pre-trained OpenPifPaf model for human pose estimation
#     predictor = openpifpaf.Predictor(checkpoint='resnet50')
#     return predictor

# def get_keypoints(pose_model, image):
#     predictions, _, _ = pose_model.numpy_image(image)

#     keypoints = []
#     if predictions:
#         for ann in predictions:
#             for i in range(0, len(ann.data), 3):
#                 x, y, confidence = ann.data[i], ann.data[i+1], ann.data[i+2]
#                 if confidence > 0.5:  # filter low confidence points
#                     keypoints.append((x / image.shape[1], y / image.shape[0]))  # normalize between [0,1]

#     return keypoints

